---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: 'Les messages d"audit échangés dans le système StorageGRID incluent des informations standard communes à tous les messages et du contenu spécifique décrivant l"événement ou l"activité signalé.' 
---
= Format du message d'audit : présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les messages d'audit échangés dans le système StorageGRID incluent des informations standard communes à tous les messages et du contenu spécifique décrivant l'événement ou l'activité signalé.

Si le résumé fourni par le link:using-audit-explain-tool.html["audit - expliquer"] et link:using-audit-sum-tool.html["somme-audit"] les outils sont insuffisants, reportez-vous à cette section pour comprendre le format général de tous les messages de vérification.

Voici un exemple de message d'audit tel qu'il peut apparaître dans le fichier journal d'audit :

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Chaque message d'audit contient une chaîne d'éléments d'attribut. L'ensemble de la chaîne est entre crochets (`[ ]`), et chaque élément d'attribut de la chaîne possède les caractéristiques suivantes :

* Entre crochets `[ ]`
* Introduit par la chaîne `AUDT`, qui indique un message d'audit
* Sans délimiteurs (pas de virgules ni d'espaces) avant ou après
* Terminé par un caractère de flux de ligne `\n`


Chaque élément inclut un code d'attribut, un type de données et une valeur qui sont rapportées dans ce format :

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
Le nombre d'éléments d'attribut dans le message dépend du type d'événement du message. Les éléments d'attribut ne sont pas répertoriés dans un ordre particulier.

La liste suivante décrit les éléments d'attribut :

* `ATTR` est un code à quatre caractères pour l'attribut en cours de signalement. Certains attributs sont communs à tous les messages d'audit et à d'autres, qui sont spécifiques à un événement.
* `type` Est un identificateur à quatre caractères du type de données de programmation de la valeur, comme UI64, FC32, etc. Le type est entre parenthèses `( )`.
* `value` est le contenu de l'attribut, généralement une valeur numérique ou de texte. Les valeurs suivent toujours deux-points (`:`). Les valeurs du type de données CSTR sont entourées de guillemets doubles " ".

