---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 11.8 utilise la version 4 de l"API de gestion des locataires. La version 4 déchiffre la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.' 
---
= Modifications apportées à l'API de gestion des locataires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.8 utilise la version 4 de l'API de gestion des locataires. La version 4 déchiffre la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.


NOTE: Vous pouvez continuer à utiliser des versions obsolètes de l'API de gestion des locataires avec StorageGRID 11.8. Cependant, la prise en charge de ces versions de l'API sera supprimée dans une future version de StorageGRID. Après la mise à niveau vers StorageGRID 11.8, les API obsolètes peuvent être désactivées à l'aide de `PUT /grid/config/management` API.

Pour en savoir plus, rendez-vous sur link:../tenant/understanding-tenant-management-api.html["Découvrez l'API de gestion des locataires"].



== Nouveaux terminaux pour les balises de règles ILM

Vous pouvez utiliser les noeuds finaux de l'API */org/ilm-policy-tags* et */org/containers/{bucketName}/ilm-policy-tags* pour effectuer des opérations liées aux balises de stratégie ILM.
