---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: Certaines fonctionnalités ont été supprimées ou obsolètes dans cette version. Consultez ces éléments pour savoir si vous devez mettre à jour les applications client ou modifier votre configuration avant de procéder à la mise à niveau. 
---
= Fonctionnalités supprimées ou obsolètes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Certaines fonctionnalités ont été supprimées ou obsolètes dans cette version. Consultez ces éléments pour savoir si vous devez mettre à jour les applications client ou modifier votre configuration avant de procéder à la mise à niveau.



== Définitions

Obsolète:: La fonction *ne devrait pas* être utilisée dans les nouveaux environnements de production. Les environnements de production existants peuvent continuer à utiliser cette fonctionnalité.
Fin de vie:: Dernière version livrée contenant la fonction. Aucune version future ne prendra en charge cette fonctionnalité.
Supprimé:: Première version que *ne contient pas* la fonction.




== Fin de la prise en charge de StorageGRID 11.8

Les fonctions obsolètes seront supprimées dans les versions majeures N+2. Par exemple, si une fonction est obsolète dans la version N (par exemple, 6.3), la dernière version où la fonction existera est N+1 (par exemple, 6.4). La version N+2 (par exemple, 6.5) est la première version lorsque la fonction n'existe pas dans le produit.

Voir la https://mysupport.netapp.com/site/info/version-support["Page de support des versions logicielles"^] pour plus d'informations.


NOTE: Dans certains cas, NetApp peut mettre fin à la prise en charge de certaines fonctionnalités plus tôt que prévu.

[cols="3a,1a,1a,1a"]
|===
| Fonction | Obsolète | Fin de vie | Supprimé 


 a| 
Prise en charge du nœud d'archivage
 a| 
11.7
 a| 
11.8
 a| 
11.9



 a| 
Exportation d'audit via CIFS/Samba
 a| 
11.1
 a| 
11.6
 a| 
11.7



 a| 
Service CLB
 a| 
11.4
 a| 
11.6
 a| 
11.7



 a| 
Exécution du conteneur Docker
 a| 
11.8
 a| 
11.9
 a| 
12.0



 a| 
Exportation d'audit NFS
 a| 
11.8
 a| 
11.9
 a| 
12.0



 a| 
Prise en charge de l'API Swift
 a| 
11.7
 a| 
11.9
 a| 
12.0

|===