---
permalink: swift/options-request.html 
sidebar: sidebar 
keywords: swift options request 
summary: 'La demande D"OPTIONS vérifie la disponibilité d"un service Swift individuel. La demande D"OPTIONS est traitée par le nœud de stockage ou le nœud passerelle spécifié dans l"URL.' 
---
= Demande D'OPTIONS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La demande D'OPTIONS vérifie la disponibilité d'un service Swift individuel. La demande D'OPTIONS est traitée par le nœud de stockage ou le nœud passerelle spécifié dans l'URL.



== Méthode DES OPTIONS

Par exemple, les applications client peuvent émettre une demande D'OPTIONS vers le port Swift sur un nœud de stockage, sans fournir d'informations d'authentification Swift, pour déterminer si le nœud de stockage est disponible. Vous pouvez utiliser cette requête pour la surveillance ou permettre aux équilibreurs de charge externes d'identifier lorsqu'un nœud de stockage est arrêté.

Lorsqu'elle est utilisée avec l'URL info ou l'URL de stockage, la méthode OPTIONS renvoie une liste de verbes pris en charge pour l'URL donnée (par exemple, HEAD, GET, OPTIONS et PUT). La méthode D'OPTIONS ne peut pas être utilisée avec l'URL d'authentification.

Le paramètre de demande suivant est requis :

* `Account`


Les paramètres de demande suivants sont facultatifs :

* `Container`
* `Object`


Une exécution réussie renvoie les en-têtes suivants avec une réponse « HTTP/1.1 204 No Content ». La demande D'OPTIONS à l'URL de stockage ne nécessite pas que la cible existe.

* `Allow` (Une liste de verbes pris en charge pour l'URL donnée, par exemple, HEAD, GET, OPTIONS, Et PUT)
* `Content-Length`
* `Content-Type`
* `Date`
* `X-Trans-Id`


.Informations associées
link:supported-swift-api-endpoints.html["Terminaux API Swift pris en charge"]
