---
permalink: swift/swift-rest-api-supported-operations.html 
sidebar: sidebar 
keywords: OpenStack, Swift API, REST API 
summary: 'Le système StorageGRID prend en charge la plupart des opérations dans l"API OpenStack Swift. Avant d"intégrer des clients de l"API REST Swift avec StorageGRID, consultez les informations d"implémentation pour les opérations des comptes, des conteneurs et des objets.' 
---
= Opérations prises en charge par l'API REST Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système StorageGRID prend en charge la plupart des opérations dans l'API OpenStack Swift. Avant d'intégrer des clients de l'API REST Swift avec StorageGRID, consultez les informations d'implémentation pour les opérations des comptes, des conteneurs et des objets.



== Opérations prises en charge par StorageGRID

Les opérations de l'API Swift suivantes sont prises en charge :

* link:account-operations.html["Opérations sur le compte"]
* link:container-operations.html["Opérations sur les conteneurs"]
* link:object-operations.html["Opérations sur l'objet"]




== En-têtes de réponse courants pour toutes les opérations

Le système StorageGRID implémente toutes les en-têtes courants pour les opérations prises en charge, comme défini par l'API de stockage objet OpenStack Swift v1.

.Informations associées
http://docs.openstack.org/developer/swift/api/object_api_v1_overview.html["OpenStack : API de stockage objet"^]
