= Rechercher le nom d'hôte pour le noeud de stockage
:allow-uri-read: 




== Rechercher le nom d'hôte pour le noeud de stockage

. Connectez-vous au nœud d'administration principal :
+
.. Saisissez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Utilisez le `/etc/hosts` Fichier pour trouver le nom d'hôte du noeud de stockage pour les volumes de stockage restaurés. Pour afficher la liste de tous les nœuds de la grille, saisissez les éléments suivants : `cat /etc/hosts`.




== Réparez les données si tous les volumes ont échoué

Si tous les volumes de stockage sont en panne, réparez l'intégralité du nœud. Suivez les instructions pour les données *répliquées*, *codées par effacement (EC)*, ou les deux, selon que vous utilisez ou non des données répliquées, des données codées par effacement (EC), ou les deux.

Si seuls certains volumes ont échoué, accédez à <<Réparer les données si seulement certains volumes ont échoué>>.


NOTE: Vous ne pouvez pas courir `repair-data` opérations simultanément pour plusieurs nœuds. Pour restaurer plusieurs nœuds, contactez le support technique.

[role="tabbed-block"]
====
.Les données répliquées
--
Si votre grid inclut des données répliquées, utilisez le `repair-data start-replicated-node-repair` commande avec `--nodes` option, où `--nodes` Est le nom d'hôte (nom du système), pour réparer la totalité du nœud de stockage.

Cette commande répare les données répliquées sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: Lorsque les données d'objet sont restaurées, l'alerte *objets perdus* est déclenchée si le système StorageGRID ne peut pas localiser les données d'objet répliquées. Des alertes peuvent être déclenchées sur les nœuds de stockage dans le système. Vous devez déterminer la cause de la perte et si la récupération est possible. Voir link:../troubleshoot/investigating-lost-objects.html["Rechercher les objets perdus"].

--
.Données avec code d'effacement (EC)
--
Si votre grid contient des données avec code d'effacement, utilisez la `repair-data start-ec-node-repair` commande avec `--nodes` option, où `--nodes` Est le nom d'hôte (nom du système), pour réparer la totalité du nœud de stockage.

Cette commande répare les données codées de l'effacement sur un nœud de stockage appelé SG-DC-SN3 :

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

L'opération renvoie un seul `repair ID` qui l'identifie `repair_data` fonctionnement. Utilisez-le `repair ID` pour suivre la progression et le résultat du `repair_data` fonctionnement. Aucun autre retour n'est renvoyé à la fin du processus de récupération.


NOTE: Les réparations des données codées peuvent commencer alors que certains nœuds de stockage sont hors ligne. La réparation s'effectuera une fois que tous les nœuds sont disponibles.

--
====


== Réparer les données si seulement certains volumes ont échoué

Si seulement certains volumes ont échoué, réparez les volumes affectés. Suivez les instructions pour les données *répliquées*, *codées par effacement (EC)*, ou les deux, selon que vous utilisez ou non des données répliquées, des données codées par effacement (EC), ou les deux.

Si tous les volumes ont échoué, accédez à <<Réparez les données si tous les volumes ont échoué>>.

Saisissez les ID de volume en hexadécimal. Par exemple : `0000` est le premier volume et `000F` est le seizième volume. Vous pouvez spécifier un volume, une plage de volumes ou plusieurs volumes qui ne sont pas dans une séquence.

Tous les volumes doivent se trouver sur le même nœud de stockage. Si vous devez restaurer des volumes pour plusieurs nœuds de stockage, contactez le support technique.

[role="tabbed-block"]
====
.Les données répliquées
--
Si votre grid contient des données répliquées, utilisez le `start-replicated-volume-repair` commande avec `--nodes` option permettant d'identifier le nœud (où `--nodes` est le nom d'hôte du nœud). Ajoutez ensuite l'une ou l'autre des `--volumes` ou `--volume-range` comme indiqué dans les exemples suivants.

*Volume unique* : cette commande restaure les données répliquées vers le volume `0002` Sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*Plage de volumes* : cette commande restaure les données répliquées vers tous les volumes de la plage `0003` à `0009` Sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*Volumes multiples non compris dans une séquence* : cette commande restaure les données répliquées vers des volumes `0001`, `0005`, et `0008` Sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: Lorsque les données d'objet sont restaurées, l'alerte *objets perdus* est déclenchée si le système StorageGRID ne peut pas localiser les données d'objet répliquées. Des alertes peuvent être déclenchées sur les nœuds de stockage dans le système. Notez la description de l'alerte et les actions recommandées pour déterminer la cause de la perte et si la récupération est possible.

--
.Données avec code d'effacement (EC)
--
Si votre grid contient des données avec code d'effacement, utilisez la `start-ec-volume-repair` commande avec `--nodes` option permettant d'identifier le nœud (où `--nodes` est le nom d'hôte du nœud). Ajoutez ensuite l'une ou l'autre des `--volumes` ou `--volume-range` comme indiqué dans les exemples suivants.

*Volume unique* : cette commande restaure les données codées par effacement dans un volume `0007` Sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*Plage de volumes* : cette commande restaure les données avec code d'effacement sur tous les volumes de la plage `0004` à `0006` Sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*Plusieurs volumes non dans une séquence* : cette commande restaure les données codées par effacement dans des volumes `000A`, `000C`, et `000E` Sur un nœud de stockage nommé SG-DC-SN3 :

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

Le `repair-data` l'opération renvoie un seul `repair ID` qui l'identifie `repair_data` fonctionnement. Utilisez-le `repair ID` pour suivre la progression et le résultat du `repair_data` fonctionnement. Aucun autre retour n'est renvoyé à la fin du processus de récupération.


NOTE: Les réparations des données codées peuvent commencer alors que certains nœuds de stockage sont hors ligne. La réparation s'effectuera une fois que tous les nœuds sont disponibles.

--
====