---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Si vous avez activé le verrouillage objet S3 lors de la création du compartiment, vous pouvez modifier ce dernier pour modifier les paramètres de conservation par défaut. Vous pouvez activer (ou désactiver) la rétention par défaut et définir un mode de rétention et une période de rétention par défaut.' 
---
= Mettre à jour la conservation par défaut du verrouillage d'objet S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez activé le verrouillage objet S3 lors de la création du compartiment, vous pouvez modifier ce dernier pour modifier les paramètres de conservation par défaut. Vous pouvez activer (ou désactiver) la rétention par défaut et définir un mode de rétention et une période de rétention par défaut.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de locataires à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous appartenez à un groupe d'utilisateurs qui possède le link:tenant-management-permissions.html["Gérez tous les compartiments ou l'autorisation d'accès racine"]. Ces autorisations remplacent les paramètres d'autorisations des stratégies de groupes ou de compartiments.
* Le verrouillage des objets S3 est activé globalement pour votre système StorageGRID et vous avez activé le verrouillage des objets S3 lorsque vous avez créé le compartiment. Voir link:using-s3-object-lock.html["Utilisez le verrouillage d'objet S3 pour conserver les objets"].


.Étapes
. Sélectionnez *Afficher les compartiments* dans le tableau de bord ou sélectionnez *STOCKAGE (S3)* > *compartiments*.
. Sélectionnez le nom du compartiment dans la table.
+
La page des détails du compartiment s'affiche.

. Dans l'onglet *Bucket options*, sélectionnez l'accordéon *S3 Object Lock*.
. En option, activez ou désactivez *rétention par défaut* pour ce compartiment.
+
Les modifications de ce paramètre ne s'appliquent pas aux objets qui se trouvent déjà dans le compartiment ni aux objets qui peuvent avoir leurs propres périodes de conservation.

. Si *Default Retention* est activé, spécifiez un *mode de rétention par défaut* pour le compartiment.
+
[cols="1a,2a"]
|===
| Mode de rétention par défaut | Description 


 a| 
La conformité
 a| 
** L'objet ne peut pas être supprimé tant que sa date de conservation jusqu'à n'est pas atteinte.
** La date de conservation de l'objet peut être augmentée, mais elle ne peut pas être réduite.
** La date de conservation de l'objet jusqu'à ne peut pas être supprimée tant que cette date n'est pas atteinte.




 a| 
La gouvernance
 a| 
** Utilisateurs avec le `s3:BypassGovernanceRetention` l'autorisation peut utiliser le `x-amz-bypass-governance-retention: true` demander à l'en-tête de contourner les paramètres de rétention.
** Ces utilisateurs peuvent supprimer une version d'objet avant d'atteindre sa date de conservation jusqu'à.
** Ces utilisateurs peuvent augmenter, diminuer ou supprimer la date de conservation d'un objet.


|===
. Si *Default Retention* est activé, spécifiez la *période de rétention par défaut* pour le compartiment.
+
La *période de conservation par défaut* indique la durée pendant laquelle les nouveaux objets ajoutés à ce compartiment doivent être conservés, à partir du moment où ils sont ingérés. Spécifiez une valeur comprise entre 1 et 36,500 jours ou entre 1 et 100 ans.

. Sélectionnez *Enregistrer les modifications*.

