---
permalink: tenant/what-platform-services-are.html 
sidebar: sidebar 
keywords: platform services 
summary: 'Les services de plateforme StorageGRID vous aident à mettre en œuvre une stratégie de cloud hybride en vous permettant d"envoyer des notifications d"événements et des copies d"objets S3 et de métadonnées d"objet à des destinations externes.' 
---
= Gérer les services de plate-forme : présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les services de plateforme StorageGRID vous aident à mettre en œuvre une stratégie de cloud hybride en vous permettant d'envoyer des notifications d'événements et des copies d'objets S3 et de métadonnées d'objet à des destinations externes.

Si l'utilisation des services de plateforme est autorisée pour votre compte de locataire, vous pouvez configurer les services suivants pour n'importe quel compartiment S3 :

Réplication CloudMirror:: Utiliser link:understanding-cloudmirror-replication-service.html["Service de réplication StorageGRID CloudMirror"] Pour mettre en miroir des objets spécifiques d'un compartiment StorageGRID vers une destination externe spécifiée.
+
--
Vous pouvez, par exemple, utiliser la réplication CloudMirror pour mettre en miroir des enregistrements client spécifiques dans Amazon S3, puis exploiter les services AWS pour analyser vos données.


NOTE: La réplication CloudMirror n'est pas prise en charge si le compartiment source est activé pour le verrouillage objet S3.

--
Notifications:: Utiliser link:understanding-notifications-for-buckets.html["notifications d'événement par compartiment"] Pour envoyer des notifications sur des actions spécifiques effectuées sur des objets à un service Amazon simple notification Service (Amazon SNS) externe spécifié.
+
--
Par exemple, vous pouvez configurer l'envoi d'alertes aux administrateurs pour chaque objet ajouté à un compartiment, où les objets représentent les fichiers de journal associés à un événement système critique.


NOTE: Bien que la notification d'événement puisse être configurée sur un compartiment avec l'option de verrouillage d'objet S3 activée, les métadonnées S3 Object Lock (conservation jusqu'à la date et état de conservation légale) des objets ne seront pas incluses dans les messages de notification.

--
Service d'intégration de la recherche:: Utilisez le link:understanding-search-integration-service.html["service d'intégration de la recherche"] Permet d'envoyer des métadonnées d'objet S3 à un index Elasticsearch spécifié pour rechercher ou analyser les métadonnées à l'aide du service externe.
+
--
Vous pouvez, par exemple, configurer des compartiments pour envoyer les métadonnées d'objet S3 vers un service Elasticsearch distant. Vous pouvez ensuite utiliser Elasticsearch pour effectuer des recherches dans des compartiments et effectuer des analyses sophistiquées des modèles présents dans les métadonnées de l'objet.


NOTE: Bien que l'intégration avec Elasticsearch puisse être configurée sur un compartiment avec l'option S3 Object Lock activée, les métadonnées S3 Object Lock (conservation jusqu'à la date et état de conservation légale) des objets ne seront pas incluses dans les messages de notification.

--


L'emplacement cible des services de plateforme étant généralement externe à votre déploiement StorageGRID, les services de plateforme vous offrent la puissance et la flexibilité offertes par l'utilisation de ressources de stockage externes, de services de notification et de services de recherche ou d'analyse pour vos données.

Toute combinaison de services de plateforme peut être configurée pour un seul compartiment S3. Par exemple, vous pouvez configurer le service CloudMirror et les notifications sur un compartiment StorageGRID S3 afin de pouvoir mettre en miroir des objets spécifiques sur Amazon simple Storage Service, tout en envoyant une notification sur chacun de ces objets à une application de surveillance tierce pour vous aider à suivre vos dépenses AWS.


TIP: L'utilisation des services de la plateforme doit être activée pour chaque compte de locataire par un administrateur StorageGRID à l'aide de Grid Manager ou de l'API de gestion du grid.



== Configuration des services de plate-forme

Les services de plateforme communiquent avec les terminaux externes que vous configurez à l'aide de link:configuring-platform-services-endpoints.html["Gestionnaire de locataires"] ou le link:understanding-tenant-management-api.html["API de gestion des locataires"]. Chaque terminal représente une destination externe, par exemple un compartiment StorageGRID S3, un compartiment Amazon Web Services, une rubrique Amazon SNS ou un cluster Elasticsearch hébergé localement, sur AWS ou ailleurs.

Après avoir créé un noeud final externe, vous pouvez activer un service de plate-forme pour un compartiment en ajoutant une configuration XML au compartiment. La configuration XML identifie les objets sur lesquels le compartiment doit agir, l'action que le compartiment doit effectuer et le point de terminaison que le compartiment doit utiliser pour le service.

Vous devez ajouter des configurations XML distinctes pour chaque service de plate-forme que vous souhaitez configurer. Par exemple :

* Si vous souhaitez que tous les objets dont les clés commencent par `/images` Pour la réplication vers un compartiment Amazon S3, vous devez ajouter une configuration de réplication dans le compartiment source.
* Si vous souhaitez également envoyer des notifications lorsque ces objets sont stockés dans le compartiment, vous devez ajouter une configuration de notifications.
* Enfin, si vous voulez indexer les métadonnées de ces objets, vous devez ajouter la configuration de notification de métadonnées utilisée pour implémenter l'intégration de la recherche.


Le format du XML de configuration est régi par les API REST S3 utilisées pour mettre en œuvre les services de plateforme StorageGRID :

[cols="1a,2a,1a"]
|===
| Service de plateforme | L'API REST S3 | Reportez-vous à la section 


 a| 
Réplication CloudMirror
 a| 
* GetBuckeReplication
* PutBuckeReplication

 a| 
* link:configuring-cloudmirror-replication.html["Réplication CloudMirror"]
* link:../s3/operations-on-buckets.htmll["Opérations sur les compartiments"]




 a| 
Notifications
 a| 
* GetBucketNotifationConfiguration
* PutBucketNotifationConfiguration

 a| 
* link:configuring-event-notifications.html["Notifications"]
* link:../s3/s3/operations-on-buckets.html["Opérations sur les compartiments"]




 a| 
Intégration de la recherche
 a| 
* CONFIGURATION DES notifications de métadonnées de compartiment
* CONFIGURATION de notification des métadonnées de compartiment

 a| 
* link:using-search-integration-service.html["Intégration de la recherche"]
* link:../s3/custom-operations-on-buckets.html["Opérations personnalisées StorageGRID"]


|===
.Informations associées
link:considerations-for-platform-services.html["Considérations relatives aux services de plateforme"]
