---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: 'Vous devez télécharger les archives d"installation de StorageGRID et extraire les fichiers.' 
---
= Téléchargez et extrayez les fichiers d'installation de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez télécharger les archives d'installation de StorageGRID et extraire les fichiers.

.Étapes
. Accédez au https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Page de téléchargements NetApp pour StorageGRID"^].
. Sélectionnez le bouton pour télécharger la dernière version ou sélectionnez une autre version dans le menu déroulant et sélectionnez *Go*.
. Connectez-vous avec le nom d'utilisateur et le mot de passe de votre compte NetApp.
. Si une instruction attention/MustRead apparaît, lisez-la et cochez la case.
+

CAUTION: Après l'installation de la version StorageGRID, vous devez appliquer les correctifs requis. Pour plus d'informations, reportez-vous à la section link:../maintain/storagegrid-hotfix-procedure.html["procédure de correctif dans les instructions de récupération et de maintenance"]

. Lisez le contrat de licence de l'utilisateur final, cochez la case, puis sélectionnez *accepter et continuer*.
. Dans la colonne *Install StorageGRID*, sélectionnez le fichier .tgz ou .zip pour VMware.
+

NOTE: Utilisez le `.zip` Fichier si vous exécutez Windows sur l'ordinateur portable de service.

. Enregistrez et extrayez le fichier d'archive.
. Choisissez les fichiers dont vous avez besoin dans la liste suivante.
+
Les fichiers dont vous avez besoin dépendent de votre topologie de grille planifiée et de la manière dont vous allez déployer votre système StorageGRID.




NOTE: Les chemins répertoriés dans la table sont relatifs au répertoire de niveau supérieur installé par l'archive d'installation extraite.

[cols="1a,1a"]
|===
| Chemin d'accès et nom de fichier | Description 


| ./vsphere/README  a| 
Fichier texte qui décrit tous les fichiers contenus dans le fichier de téléchargement StorageGRID.



| ./vsphere/NLF000000.txt  a| 
Licence gratuite qui ne fournit aucun droit d'assistance pour le produit.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
Fichier de disque de machine virtuelle utilisé comme modèle pour créer des machines virtuelles de nœud de grille.



| ./vsphere/vsphere-primary-admin.ovf

./vsphere/vsphere-primary-admin.mf  a| 
Fichier modèle du format Open Virtualization (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement du nœud d'administration principal.



| ./vsphere/vsphere-non-primary-admin.ovf

./vsphere/vsphere-non-primary-admin.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement de nœuds d'administration non primaires.



| ./vsphere/vsphere-archive.ovf

./vsphere/vsphere-archive.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement des nœuds d'archivage.



| ./vsphere/vsphere-gateway.ovf

./vsphere/vsphere-gateway.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement des nœuds de passerelle.



| ./vsphere/vsphere-storage.ovf

./vsphere/vsphere-storage.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement de nœuds de stockage basés sur des machines virtuelles.



| Outil de script de déploiement | Description 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Script de shell de Bash utilisé pour automatiser le déploiement de nœuds de grille virtuels.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Exemple de fichier de configuration à utiliser avec `deploy-vsphere-ovftool.sh` script.



| ./vsphere/configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration d'un système StorageGRID.



| ./vsphere/configure-sga.py  a| 
Script Python utilisé pour automatiser la configuration des appliances StorageGRID.



| ./vsphere/storagegrid-ssoauth.py  a| 
Exemple de script Python que vous pouvez utiliser pour vous connecter à l'API de gestion de grille lorsque l'authentification unique (SSO) est activée. Vous pouvez également utiliser ce script pour le Federate Ping.



| ./vsphere/configure-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec `configure-storagegrid.py` script.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un fichier de configuration vierge à utiliser avec le `configure-storagegrid.py` script.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Exemple de script Python que vous pouvez utiliser pour vous connecter à l'API de gestion de grille lorsque l'authentification unique (SSO) est activée à l'aide d'Active Directory ou de Ping Federate.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
Script d'aide appelé par le compagnon `storagegrid-ssoauth-azure.py` Script Python pour effectuer des interactions SSO avec Azure.



| ./vsphere/extras/schémas-api  a| 
Schémas API pour StorageGRID.

*Remarque* : avant d'effectuer une mise à niveau, vous pouvez utiliser ces schémas pour confirmer que tout code que vous avez écrit pour utiliser les API de gestion StorageGRID sera compatible avec la nouvelle version de StorageGRID si vous ne disposez pas d'un environnement StorageGRID non productif pour le test de compatibilité de mise à niveau.

|===