---
permalink: admin/adding-nfs-audit-client-to-audit-share.html 
sidebar: sidebar 
keywords: nfs, audit client, audit share 
summary: 'Les clients d"audit NFS ont accès à un partage d"audit en fonction de leur adresse IP. Accorder l"accès au partage d"audit à un nouveau client d"audit NFS en ajoutant son adresse IP au partage d"audit.' 
---
= Ajouter un client d'audit NFS à un partage d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les clients d'audit NFS ont accès à un partage d'audit en fonction de leur adresse IP. Accorder l'accès au partage d'audit à un nouveau client d'audit NFS en ajoutant son adresse IP au partage d'audit.


NOTE: La prise en charge de NFS est obsolète et sera supprimée dans une future version.

.Avant de commencer
* Vous avez le `Passwords.txt` avec le mot de passe du compte root/admin.
* Vous avez le `Configuration.txt` Fichier (disponible dans le progiciel de récupération).
* Le client d'audit utilise NFS version 3 (NFSv3).


.Étapes
. Connectez-vous au nœud d'administration principal :
+
.. Saisissez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Démarrez l'utilitaire de configuration NFS : `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. Entrez : `add-ip-to-share`
+
La liste des partages d'audit NFS activés sur le nœud d'administration s'affiche. Le partage d'audit est répertorié comme suit : `/var/local/log`

. Entrez le numéro du partage d'audit : `_audit_share_number_`
. Lorsque vous y êtes invité, entrez l'adresse IP ou la plage d'adresses IP du client d'audit pour le partage d'audit : `_client_IP_address_`
+
Le client d'audit est ajouté au partage d'audit.

. Lorsque vous y êtes invité, appuyez sur *entrée*.
+
L'utilitaire de configuration NFS s'affiche.

. Répétez les étapes pour chaque client d'audit qui doit être ajouté au partage d'audit.
. Vérifiez éventuellement votre configuration : `validate-config`
+
Les services sont vérifiés et affichés.

+
.. Lorsque vous y êtes invité, appuyez sur *entrée*.
+
L'utilitaire de configuration NFS s'affiche.



. Fermez l'utilitaire de configuration NFS : `exit`
. Si le déploiement de StorageGRID est un site unique, passez à l'étape suivante.
+
Si le déploiement StorageGRID inclut des nœuds d'administration sur d'autres sites, activez éventuellement ces partages d'audit si nécessaire :

+
.. Connectez-vous à distance au nœud d'administration d'un site :
+
... Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour passer à la racine : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


.. Répétez cette procédure pour configurer les partages d'audit pour chaque nœud d'administration.
.. Fermez la connexion du shell sécurisé distant au nœud d'administration distant : `exit`


. Déconnectez-vous du shell de commande : `exit`

