---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: 'Si vous souhaitez conserver les informations historiques relatives aux attributs, aux alarmes et aux alertes sur un nœud d"administration non primaire qui a échoué, vous pouvez restaurer la base de données du nœud d"administration à partir du nœud d"administration principal.' 
---
= Restaurez la base de données du nœud d'administration lors de la restauration d'un nœud d'administration non primaire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez conserver les informations historiques relatives aux attributs, aux alarmes et aux alertes sur un nœud d'administration non primaire qui a échoué, vous pouvez restaurer la base de données du nœud d'administration à partir du nœud d'administration principal.

.Avant de commencer
* Le nœud d'administration récupéré est installé et en cours d'exécution.
* Le système StorageGRID comprend au moins deux nœuds d'administration.
* Vous avez le `Passwords.txt` fichier.
* Vous avez la phrase secrète pour le provisionnement.


.Description de la tâche
En cas de défaillance d'un nœud d'administration, les informations historiques stockées dans sa base de données de nœud d'administration sont perdues. Cette base de données contient les informations suivantes :

* Historique des alertes
* Historique des alarmes
* Les données d'attributs historiques, qui sont utilisées dans les graphiques et les rapports texte disponibles à partir de la page *SUPPORT* > *Outils* > *topologie de grille*.


Lorsque vous restaurez un noeud d'administration, le processus d'installation du logiciel crée une base de données de noeud d'administration vide sur le noeud récupéré. Toutefois, la nouvelle base de données comprend uniquement les informations pour les serveurs et services qui font actuellement partie du système ou qui sont ajoutés ultérieurement.

Si vous avez restauré un noeud d'administration non primaire, vous pouvez restaurer les informations d'historique en copiant la base de données du noeud d'administration principal (le noeud d'administration _source_) vers le noeud récupéré.


NOTE: La copie de la base de données du nœud d'administration peut prendre plusieurs heures. Certaines fonctions de Grid Manager ne seront pas disponibles lorsque les services sont arrêtés sur le nœud source.

.Étapes
. Connectez-vous au nœud d'administration source :
+
.. Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


. Exécutez la commande suivante depuis le nœud d'administration source. Saisissez ensuite la phrase de passe de provisionnement si vous y êtes invité. `recover-access-points`
. Depuis le nœud d'administration source, arrêtez le service MI : `service mi stop`
. Depuis le nœud d'administration source, arrêtez le service Management application Program interface (mgapi) : `service mgmt-api stop`
. Effectuez les étapes suivantes sur le nœud d'administration restauré :
+
.. Connectez-vous au nœud d'administration restauré :
+
... Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour passer à la racine : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


.. Arrêtez le service MI : `service mi stop`
.. Arrêt du service mgmt-api : `service mgmt-api stop`
.. Ajoutez la clé privée SSH à l'agent SSH. Entrez :``ssh-add``
.. Entrez le mot de passe d'accès SSH répertorié dans le `Passwords.txt` fichier.
.. Copiez la base de données du nœud d'administration source vers le nœud d'administration restauré : `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. Lorsque vous y êtes invité, confirmez que vous souhaitez remplacer la base DE données MI sur le nœud d'administration restauré.
+
La base de données et ses données historiques sont copiées dans le nœud d'administration restauré. Une fois l'opération de copie effectuée, le script démarre le nœud d'administration restauré.

.. Lorsque vous n'avez plus besoin d'un accès sans mot de passe à d'autres serveurs, supprimez la clé privée de l'agent SSH. Entrez :``ssh-add -D``


. Redémarrez les services sur le nœud d'administration source : `service servermanager start`

